### ISSUE TITLE
haskell-style-guide

### ISSUE THREAD

**Issue by superbobry** [nilcons/hi2#2]
Is it possible to make `hi2` provide indentation similar to the one described in [`haskell-style-guide`](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md)?

**Comment by hvr** [comment]
Fyi, this works the same way as with `haskell-indentation` which `hi2` is derived from, i.e. by customizing the following variables (use <kbd>M-x customize-group [RET] hi2</kbd> for that):

``` el
;; Note: this variables should be set buffer local!
(setq hi2-layout-offset 4
      hi2-left-offset 4
      hi2-ifte-offset 4)
```

However, what doesn't seem possible yet is setting the indentation of the initial guard to 2 spaces (so that it aligns with the `where` clause) according to the [`haskell-style-guide` variation as used by the Snap framework](http://snapframework.com/docs/style-guide)

**Comment by superbobry** [comment]
Thanks, but even with the settings above record types are indented incorrectly:

``` haskell
data Foo = Foo
           { fooBar :: Int, ... }  -- try pressing TAB on this line.
```

**Comment by errge** [comment]
Thanks for reporting these issues.  Instead of just referring me to the haskell-style-guide, if you have issues, please provide concrete examples where the mode works incorrectly, like you provided in the last comment.  It's a lot easier to look into concrete issues than to learn other people coding styles just to compare to the current parser.  What would be the wanted behavior after Foo?  To indent it two spaces more?

And hvr is totally right, currently the parser is not changed in any significant way compared to haskell-indentation-mode.  I plan to look into it on http://www.haskell.org/haskellwiki/ZuriHac2013, so maybe I'll fix these two issues then.

Thanks again for testing this!

**Comment by superbobry** [comment]
> What would be the wanted behavior after Foo? To indent it two spaces more?

The wanted behaviour is:

``` haskell
data Foo = Foo
    { fooBar :: Int, ... } 
```

I'll move the discussion to a more concrete issue, thank you!
